//
// Automatically generated by gen-bit-packers, do not edit
//
#ifndef __CXXU_PACK_PACK_UNPACK_16_H__
#define __CXXU_PACK_PACK_UNPACK_16_H__

#include <stdint.h>

#include <timevault/config.h>

namespace cxxu {
namespace pack {

typedef
void
(*packer_16_ptr)(
    uint16_t* __restrict__ out,
    const uint16_t* __restrict__ in,
    uint32_t n
);
extern TIMEVAULT_API packer_16_ptr packer_16_table[16];
extern TIMEVAULT_API packer_16_ptr packer_16_simd_table[16];

typedef
void
(*unpacker_16_ptr)(
    uint16_t* __restrict__ out,
    const uint16_t* __restrict__ in,
    uint32_t n
);
extern TIMEVAULT_API unpacker_16_ptr unpacker_16_table[16];
extern TIMEVAULT_API unpacker_16_ptr unpacker_16_simd_table[16];

} // namespace pack
} // namespace cxxu

#endif // __CXXU_PACK_PACK_UNPACK_16_H__
