//
// Automatically generated by gen-bit-packers, do not edit
//
#ifndef __CXXU_PACK_PACK_UNPACK_8_H__
#define __CXXU_PACK_PACK_UNPACK_8_H__

#include <stdint.h>

#include <cxxutils/config.h>

namespace cxxu {
namespace pack {

typedef
void
(*packer_8_ptr)(
    uint8_t* __restrict__ out,
    const uint8_t* __restrict__ in,
    uint32_t n
);
extern CXXUTILS_API packer_8_ptr packer_8_table[8];
extern CXXUTILS_API packer_8_ptr packer_8_simd_table[8];

typedef
void
(*unpacker_8_ptr)(
    uint8_t* __restrict__ out,
    const uint8_t* __restrict__ in,
    uint32_t n
);
extern CXXUTILS_API unpacker_8_ptr unpacker_8_table[8];
extern CXXUTILS_API unpacker_8_ptr unpacker_8_simd_table[8];

} // namespace pack
} // namespace cxxu

#endif // __CXXU_PACK_PACK_UNPACK_8_H__
