//
// Automatically generated by gen-bit-packers, do not edit
//
#ifndef __CXXU_PACK_PACK_UNPACK_32_H__
#define __CXXU_PACK_PACK_UNPACK_32_H__

#include <stdint.h>

#include <cxxutils/config.h>

namespace cxxu {
namespace pack {

typedef
void
(*packer_32_ptr)(
    uint32_t* __restrict__ out,
    const uint32_t* __restrict__ in,
    uint32_t n
);
extern CXXUTILS_API packer_32_ptr packer_32_table[32];
extern CXXUTILS_API packer_32_ptr packer_32_simd_table[32];

typedef
void
(*unpacker_32_ptr)(
    uint32_t* __restrict__ out,
    const uint32_t* __restrict__ in,
    uint32_t n
);
extern CXXUTILS_API unpacker_32_ptr unpacker_32_table[32];
extern CXXUTILS_API unpacker_32_ptr unpacker_32_simd_table[32];

} // namespace pack
} // namespace cxxu

#endif // __CXXU_PACK_PACK_UNPACK_32_H__
